# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndexWindow(object):
    def setupUi(self, IndexWindow):
        IndexWindow.setObjectName("IndexWindow")
        IndexWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(IndexWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 90, 331, 31))
        self.lineEdit.setToolTipDuration(1)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 140, 331, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 110, 58, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 90, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 220, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 100, 101, 16))
        self.label_4.setToolTip("")
        self.label_4.setStyleSheet("color:red;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 150, 101, 16))
        self.label_5.setToolTip("")
        self.label_5.setStyleSheet("color:red;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 50, 101, 16))
        self.label_6.setToolTip("")
        self.label_6.setStyleSheet("color:red;")
        self.label_6.setObjectName("label_6")
        IndexWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IndexWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        IndexWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IndexWindow)
        self.statusbar.setObjectName("statusbar")
        IndexWindow.setStatusBar(self.statusbar)

        self.retranslateUi(IndexWindow)
        QtCore.QMetaObject.connectSlotsByName(IndexWindow)

    def retranslateUi(self, IndexWindow):
        _translate = QtCore.QCoreApplication.translate
        IndexWindow.setWindowTitle(_translate("IndexWindow", "跨境搜搜索"))
        self.lineEdit.setToolTip(_translate("IndexWindow", "账号不能为空"))
        self.label_2.setText(_translate("IndexWindow", "账号："))
        self.label_3.setText(_translate("IndexWindow", "密码："))
        self.pushButton.setText(_translate("IndexWindow", "立即登录"))
        self.label_4.setText(_translate("IndexWindow", "账号不能为空"))
        self.label_5.setText(_translate("IndexWindow", "密码不能为空"))
        self.label_6.setText(_translate("IndexWindow", "登录失败"))
